# Generated by Django 4.0.6 on 2022-07-20 18:53

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ong",
            fields=[
                (
                    "ong_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, null=True, unique=True)),
                (
                    "description",
                    models.CharField(max_length=255, null=True, unique=True),
                ),
                ("cnpj", models.CharField(max_length=14, null=True, unique=True)),
                ("site_address", models.CharField(max_length=255)),
                ("logo", models.CharField(max_length=255, null=True)),
                ("created_at", models.DateField(auto_now=True)),
            ],
        ),
    ]
