# Generated by Django 4.0.6 on 2022-07-26 04:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ongs", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("causes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ong",
            name="admins",
            field=models.ManyToManyField(
                related_name="ongs", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="ong",
            name="causes",
            field=models.ManyToManyField(related_name="ongs", to="causes.cause"),
        ),
    ]
