# Generated by Django 4.0.6 on 2022-07-25 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ongs", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ong",
            name="cnpj",
            field=models.CharField(max_length=18, null=True, unique=True),
        ),
    ]
