# Generated by Django 4.0.6 on 2022-07-25 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ongs", "0003_alter_ong_cnpj"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ong",
            name="description",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
